# Generated by Django 4.2.6 on 2023-11-24 07:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeModel',
            fields=[
                ('employee_id', models.IntegerField(primary_key=True, serialize=False)),
                ('employee_name', models.CharField(max_length=255)),
                ('employee_role', models.CharField(max_length=255, null=True)),
                ('employee_position', models.CharField(max_length=255, null=True)),
                ('date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('employee_phone', models.CharField(max_length=255, null=True)),
                ('email', models.EmailField(max_length=254)),
                ('gender', models.CharField(max_length=255)),
                ('experience', models.IntegerField(default=0)),
                ('employee_date_of_join', models.DateField(default=django.utils.timezone.now)),
                ('martial_status', models.CharField(max_length=255)),
                ('nationality', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LeavesModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_annual_leaves', models.IntegerField()),
                ('leaves_consumed', models.IntegerField()),
                ('total_sick_leaves', models.IntegerField()),
                ('sick_leaves_consumed', models.IntegerField()),
                ('total_casual_leaves', models.IntegerField(default=24)),
                ('casual_leaves_consumed', models.IntegerField(default=0)),
                ('unpaid_leaves_consumed', models.IntegerField(default=0)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employeemodel')),
            ],
        ),
        migrations.CreateModel(
            name='LeavesHistoryModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateField(default=django.utils.timezone.now)),
                ('to_date', models.DateField(default=django.utils.timezone.now)),
                ('number_of_days', models.IntegerField()),
                ('approved_by', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=255)),
                ('leave_type', models.CharField(max_length=255)),
                ('reason', models.TextField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employeemodel')),
                ('notify', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='leave_notifications', to='login.employeemodel')),
            ],
        ),
        migrations.CreateModel(
            name='FileUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='uploads/')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employeemodel')),
            ],
        ),
    ]
