# Generated by Django 4.2.6 on 2023-11-28 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayCalenderModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date', models.DateField()),
                ('is_floater', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='AttendenceLogModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('check_in_date', models.DateField()),
                ('check_in_time', models.DateTimeField()),
                ('check_out_time', models.DateTimeField()),
                ('effective_hours', models.DurationField()),
                ('gross_hours', models.DurationField()),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='login.employeemodel')),
            ],
        ),
    ]
