# Generated by Django 4.2.5 on 2023-11-16 10:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_fileupload'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeemodel',
            name='employeeDateOfJoin',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='employeePhone',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='employeeRole',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='employeemodel',
            name='experience',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employeemodel',
            name='dateOfBirth',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
