# Generated by Django 4.2.6 on 2023-11-29 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_holidaycalendermodel_attendencelogmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendencelogmodel',
            name='check_out_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendencelogmodel',
            name='effective_hours',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='attendencelogmodel',
            name='gross_hours',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
