# Generated by Django 4.2.6 on 2023-11-23 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_fileupload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fileupload',
            name='employee',
            field=models.ForeignKey(default=20231, on_delete=django.db.models.deletion.CASCADE, to='login.employeemodel'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='leaveshistorymodel',
            name='approved_by',
            field=models.ForeignKey(default=20231, on_delete=django.db.models.deletion.CASCADE, related_name='approve_notifications', to='login.employeemodel'),
        ),
        migrations.AlterField(
            model_name='leaveshistorymodel',
            name='notify',
            field=models.ForeignKey(default=20231, on_delete=django.db.models.deletion.CASCADE, related_name='leave_notifications', to='login.employeemodel'),
        ),
    ]
